[package]
authors = ["Moody <mooodyhunter@outlook.com>"]
edition = "2021"
name = "cam_agent"
version = "0.1.0"

[dependencies]
prost = "0.10.0"
prost-types = "0.9.0"
rust-ini = "0.18.0"
tokio = {version = "1.17.0", features = ["rt-multi-thread"]}
tonic = {version = "0.6.2", features = ["transport", "tls", "tls-roots", "compression"]}

[build-dependencies]
protoc-rust-grpc = "0.8.2"
tonic-build = {version = "0.6.2", features = ["compression"]}

[[bin]]
name = "cam_agent"
path = "src/main.rs"
