[package]
authors = ["Moody <mooodyhunter@outlook.com>"]
edition = "2021"
name = "cam_agent"
version = "0.1.0"

[dependencies]
once_cell = "1.12.0"
prost = "0.10.0"
prost-types = "0.11.0"
rust-ini = "0.18.0"
tokio = {version = "1.17.0", features = ["rt-multi-thread", "macros"]}
tonic = {version = "0.7.1", features = ["transport", "tls", "tls-roots", "compression"]}

[build-dependencies]
protoc-rust-grpc = "0.8.2"
tonic-build = {version = "0.7.0", features = ["compression"]}

[[bin]]
name = "cam_agent"
path = "src/main.rs"
