[package]
authors = ["Moodyhunter <moodyhunter@outlook.com>"]
edition = "2021"
name = "notify_client"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
notify-rust = "4"
platform-dirs = "0.3.0"
rust-ini = "0.18.0"
tokio = {version = "1.17.0", features = ["rt-multi-thread"]}
tonic = {version = "0.6.2", features = ["transport", "tls", "tls-roots", "compression"]}

# Do not change to 0.10 yet
prost = "0.10.0"
prost-types = "0.9.0"

[build-dependencies]
protoc-rust-grpc = "0.8.2"
tonic-build = {version = "*", features = ["compression"]}
