name: Build Client

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-client.yml"
      - "Client/**"
      - "proto/**"

jobs:
  build:
    runs-on: azure
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - run: |
          export QT_VERSION="6.3.0"
          export APK_ARCH="android_arm64_v8a"
          export VCPKG_TRIPLET="arm64-android"
          export CI_RESOURCES="/mnt/disk/ci"

          export PATH="$PATH:$CI_RESOURCES/vcpkg/installed/x64-linux/tools/grpc"
          export PATH="$PATH:$CI_RESOURCES/vcpkg/installed/x64-linux/tools/protobuf"

          export ANDROID_SDK="$CI_RESOURCES/android-sdk"
          export ANDROID_NDK="$ANDROID_SDK/ndk/23.1.7779620"

          cd Client
          export BUILD_DIR="/tmp/moodyapi-client-build"
          mkdir -p "$BUILD_DIR"

          $CI_RESOURCES/Qt6/$QT_VERSION/$APK_ARCH/bin/qt-cmake -B "$BUILD_DIR" \
            -DQT_CHAINLOAD_TOOLCHAIN_FILE=$CI_RESOURCES/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DVCPKG_TARGET_TRIPLET=$VCPKG_TRIPLET \
            -DQT_HOST_PATH=$CI_RESOURCES/Qt6/$QT_VERSION/gcc_64/ \
            -DANDROID_SDK_ROOT=$ANDROID_SDK \
            -DANDROID_NDK_ROOT=$ANDROID_NDK \
            -DANDROID_PLATFORM=30 \
            -DCMAKE_BUILD_TYPE=Release \
            -GNinja
          cmake --build "$BUILD_DIR" --parallel
          cp -v /tmp/moodyapi-client-build/android-build/MoodyAppMain.apk ./
