name: Build Server

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-server.yml"
      - "Server/**"
      - "proto/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          export REVISION="$(git rev-parse --short HEAD)"
          cd Server
          go generate
          go build -v -o apiserver -ldflags="-X 'api.mooody.me/common.ServerRevision=$REVISION'"

      - name: Deploy
        run: |
          sudo /usr/bin/systemctl stop moodyapi-server.service
          cp -v ./Server/apiserver /mnt/moodyapi/apiserver
          sudo /usr/bin/systemctl start moodyapi-server.service
