name: Build Notifier Client on RPi

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-notifier-pi.yml"
      - "Notifier/**"
      - "MoodyAPI.proto"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: raspberrypi
    steps:
      - uses: actions/checkout@v3

      - name: Copy to Working Directory
        run: |
          rsync -aP --exclude='.git' --exclude='target' . /opt/actions/

      - name: Build
        run: |
          cd /opt/actions/Notifier
          cargo build --release
