name: Build Client

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-client.yml"
      - "Client/**"
      - "MoodyAPI.proto"

jobs:
  build:
    runs-on: azure
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - run: |
          export QT_VERSION="6.3.0"
          export APK_ARCH="android_arm64_v8a"
          export VCPKG_TRIPLET="arm64-android"
          export CI_RESOURCES="/mnt/disk/ci"

          export PATH="$PATH:$CI_RESOURCES/vcpkg/installed/x64-linux/tools/grpc"
          export PATH="$PATH:$CI_RESOURCES/vcpkg/installed/x64-linux/tools/protobuf"

          export ANDROID_SDK="$CI_RESOURCES/android-sdk"
          export ANDROID_NDK="$ANDROID_SDK/ndk/23.1.7779620"

          cd Client
          mkdir build && cd build

          $CI_RESOURCES/Qt6/$QT_VERSION/$APK_ARCH/bin/qt-cmake .. \
            -DQT_CHAINLOAD_TOOLCHAIN_FILE=$CI_RESOURCES/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DVCPKG_TARGET_TRIPLET=$VCPKG_TRIPLET \
            -DQT_HOST_PATH=$CI_RESOURCES/Qt6/$QT_VERSION/gcc_64/ \
            -DANDROID_SDK_ROOT=$ANDROID_SDK \
            -DANDROID_NDK_ROOT=$ANDROID_NDK \
            -DANDROID_PLATFORM=30 \
            -DCMAKE_BUILD_TYPE=Release \
            -GNinja
          cmake --build . --parallel

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Send APK to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{ steps.vars.outputs.sha_short }}: Successfully built the client app.
          document: Client/build/android-build/MoodyAppMain.apk
