name: Build Server

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-server.yml'
      - 'Server/**'

jobs:
  build:
    runs-on: azure
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        cd Server
        go generate
        go build -v -o apiserver
