name: Build Server

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-server.yml"
      - "Server/**"
      - "MoodyAPI.proto"

jobs:
  build:
    runs-on: azure
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          cd Server
          go generate
          go build -v -o apiserver

      - name: Deploy
        run: |
          sudo /usr/bin/systemctl stop moodyapi-server.service
          cp -v ./Server/apiserver /mnt/disk/moodyapi/apiserver
          sudo /usr/bin/systemctl start moodyapi-server.service

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Send Message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{ steps.vars.outputs.sha_short }}: Successfully deployed the API server.
