name: Build Camera Agent

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-agent.yml"
      - "CameraAgent/**"
      - "MoodyAPI.proto"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: raspberrypi
    steps:
      - uses: actions/checkout@v3

      - name: Copy to Working Directory
        run: |
          rsync -aP --exclude='.git' --exclude='target' . /opt/actions/

      - name: Build
        run: |
          cd /opt/actions/CameraAgent
          cargo build --release
          sudo systemctl stop moodyapi-agent.service
          cp ./target/release/cam_agent /opt/moodyapi/cam_agent
          sudo systemctl start moodyapi-agent.service
