name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: raspberrypi
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...
