name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'QmlApp/**'
      - '.github/workflows/build-apk.yml'

jobs:

  build:
    runs-on: azure
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        cd APIServer
        go generate
        go build -v -o apiserver
