name: Lint WebPanel

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd WebPanel/ && yarn install
    - run: cd WebPanel/ && yarn lint
    - run: cd WebPanel/ && yarn build
