name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install protoc
        run: sudo apt install protobuf-compiler

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          check-latest: true

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Update and Push
        run: |
          ./update-deps.sh
          git diff --word-diff
          git commit -am "update dependencies" && git push origin main || exit 0
